### ISSUE TITLE
cannot enter text in Sigma Access Token or Sigma FileId field

### ISSUE THREAD

**Issue by cacaosteve** [jsuarezruiz/figma-to-maui-graphics#4]
I compiled and ran FigmaSharp.Maui.Graphics.Sample with Visual Studio for Mac Preview 17.4 build 1583 and ran in Mac Catalyst.

The FigmaSharp.Maui.Graphics.Sample window appears but I cannot click or type anything in the Figma Access Token or Figma FileId fields.

**Comment by CharafHormi** [comment]
That seems to be an issue with the loading ActivityIndicator Grid, you can either set it's InputTranparent to true, or bind its visibility to IsGenerating

**Comment by jsuarezruiz** [comment]
Fixes by https://github.com/jsuarezruiz/figma-to-maui-graphics/pull/6
