### ISSUE TITLE
I have idea to make Fluent Design controls for MAUI

### ISSUE THREAD

**Issue by DmitryBorodiy** [jsuarezruiz/figma-to-maui-graphics#7]
I have app for Windows(UWP based) and need to implement it on other platforms with MAUI. Can I use official WinUI Toolkit for Figma and MAUI to do that?

**Comment by jsuarezruiz** [comment]
You can generate drawn UI based on Fluent, but the tool only gives you the code to draw. You need to create controls, manage states, events, etc.
